[package]
name = "Unity2Many"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_asset_loader = "0.20.2"
bevy_gltf_blueprints = "0.10.2"
bevy_gltf_components = "0.5.1"
bevy_registry_export = "0.3.1"
